# Configuration template for Overture Maps to ArcGIS pipelines, copy for your own use

# Country/Region Metadata (Top-level)
country:
  name: "Afghanistan"            # Full country name for titles
  iso2: "af"                    # 2-letter ISO code
  iso3: "afg"                   # 3-letter ISO code for tags
  region: "mena"          # Regional classification
  bbox: [60.5, 29.4, 74.9, 38.5]  # [min_lon, min_lat, max_lon, max_lat]

# Data Source Configuration
overture:
  base_url: "s3://overturemaps-us-west-2/release"
  s3_region: "us-west-2"
  release: "2024-11-13.0"

# Organization Metadata Templates
organization:
  name: "Ryan Arias Delafosse"
  contact_email: "rariasdelafosse@worldbank.org"
  attribution: "World Bank Group"
  license: "Internal use only. External sharing requires approval."
  update_frequency: "Monthly"

# Global Content Templates (Using dynamic variables) You have to use HTML for it to appear correctly in AGOL.
templates:
  title: "{country_name} {sector_title} - Overture Maps"
  snippet: "{country_name} {sector_description} from Overture Maps."
  description: "
    {sector_title} data for {country_name} from Overture Maps {release} release.<br><br>
    <b>Data Type:</b> {data_type}<br>
    <b>Geographic Coverage:</b> {country_name} ({iso3})<br>
    <b>Source:</b> Overture Maps Foundation<br>
    <b>Processing:</b> Overture to AGOL data pipeline. You can find the processing pipeline on GitHub <a href=\"https://github.com/worldbank/Overture-ArcGIS-Pipeline\" target=\"_blank\" rel=\"noopener noreferrer\">here</a>.<br>
    <b>Release Date:</b> {release}<br>
    <b>Update Frequency:</b> {update_frequency}<br><br>
    This dataset provides comprehensive {sector_description} information for {country_name}, processed through an automated data pipeline following organizational data standards.<br><br>
    
    <b>Usage & Attribution</b><br>
    Use consistent with Overture’s license and attribution guidance. Some Overture themes incorporate third‑party sources with additional requirements—see the Overture attribution page for theme‑level details.<br>
    <b>Contact:</b> {contact_email}<br>
    <b>Last Updated:</b> {current_date}
    "
  license_info: "{license}<br>
    © Overture Maps Foundation and contributors. Licensed under CDLA‑Permissive‑2.0.<br> 
    Some Overture themes may include third‑party sources with additional attribution or terms. <br>
    World Bank processing and value‑added metadata © {current_year} International Bank for Reconstruction and Development / The World Bank.<br>
    "
  # Base tags template: ISO3 + sector + source + year + organization tags
  tags_base: ["{iso3}", "overture maps", "public"]

# Spatial Filtering Configuration
selector:
  by: division_country  # or "bbox_only" for development
  iso2: "{iso2}"       # Will be populated from country.iso2

# Queries and Specific Metadata
targets:
  roads:
    # Data Selection
    theme: transportation
    type: segment
    #filter: "class IN ('motorway', 'trunk', 'primary', 'secondary')"  # Major roads only filter if uncommented
    
    # Sector-specific Variables
    sector_title: "Road Network"
    sector_description: "road infrastructure"
    sector_tag: "roads"
    data_type: "Transportation Infrastructure"
    
    # ArcGIS Online Configuration
    agol:
      # Core Fields (will be templated)
      item_title: "{title}"
      snippet: "{snippet}"
      description: "{description}"
      
      # Tags: base + sector-specific
      tags: "{tags_base} + ['transportation', 'roads']"
      
      # ESRI Enterprise Metadata
      access_information: "{access_information}"
      license_info: "{license_info}"
      
      # Technical Configuration
      upsert_key: "id"
      # item_id: "45e41c3c7b3e4c5692858522d2ae53f7"  # Existing layer

  education:
    # Data Selection  
    theme: places
    type: place
    filter: "categories.primary = 'education'"
    building_filter: "class IN ('college', 'kindergarten', 'school', 'university')"
    
    # Sector-specific Variables
    sector_title: "Education Facilities"
    sector_description: "educational institutions and facilities"
    sector_tag: "education"
    data_type: "Educational Infrastructure"
    
    # ArcGIS Online Configuration
    agol:
      item_title: "{title}"
      snippet: "{snippet}"
      description: "{description}"
      tags: "{tags_base} + ['education', 'scorecard_education']"
      access_information: "{access_information}"
      license_info: "{license_info}"
      upsert_key: "id"
      # item_id: "426a65f299984d68a6c612f8054f9984"  # Created layer

  health:
    # Data Selection
    theme: places
    type: place
    filter: "categories.primary = 'health_and_medical'"
    building_filter: "class IN ('medical', 'hospital')"
    
    # Sector-specific Variables
    sector_title: "Health Facilities"
    sector_description: "healthcare facilities and medical services"
    sector_tag: "health"
    data_type: "Healthcare Infrastructure"
    
    # ArcGIS Online Configuration
    agol:
      item_title: "{title}"
      snippet: "{snippet}"
      description: "{description}"
      tags: "{tags_base} + ['scorecard_health', 'health facilities']"
      access_information: "{access_information}"
      license_info: "{license_info}"
      upsert_key: "id"
      # item_id: "4a8198bf765f40cab70ebc88206d48ed"  # Old version - will create new one with better fields

  markets:
    # Data Selection
    theme: places
    type: place
    filter: "categories.primary = 'retail'"
    building_filter: "class IN ('commercial', 'retail', 'supermarket', 'kiosk')"
    
    # Sector-specific Variables
    sector_title: "Marketplaces & Retail Facilities"
    sector_description: "commercial markets and retail facilities"
    sector_tag: "markets"
    data_type: "Commercial Infrastructure"
    
    # ArcGIS Online Configuration
    agol:
      item_title: "{title}"
      snippet: "{snippet}" 
      description: "{description}"
      tags: "{tags_base} + ['markets', 'scorecard_investment', 'scorecard_community']"
      access_information: "{access_information}"
      license_info: "{license_info}"
      upsert_key: "id"
      # item_id: "" # Will be populated after first upload

  places:
    # Data Selection
    theme: places
    type: place
    # No filter - all places
    
    # Sector-specific Variables
    sector_title: "All Places"
    sector_description: "comprehensive points of interest and places"
    sector_tag: "places"
    data_type: "Points of Interest"
    
    # ArcGIS Online Configuration
    agol:
      item_title: "{title}"
      snippet: "{snippet}"
      description: "{description}"
      tags: "{tags_base} + ['places', 'poi', 'locations', 'amenities']"
      access_information: "{access_information}"
      license_info: "{license_info}"
      upsert_key: "id"
      # item_id: "" # Will be populated after first upload